- source/manual/hardware.rst
Initial request here:
https://www.reddit.com/r/OPNsenseFirewall/comments/7v22r7/opnsense_freebsd_rebase_and_hardware_tree_support/
> Updated FreeBSD version in hardware.rst

- source/manual/how-tos/sslvpn_client.rst
ref: https://forum.opnsense.org/index.php?topic=7314.msg33402#msg33402
> fix sslvpn_client.rst (wrong information about TOTP)

- source/manual/how-tos/shaper.rst
> fix masks in shaper howto

- source/development/guidelines/basics.rst
Hi there,
I fixed some minor issues and added some links for the "Basics and Future" page.
Cheers,
tpltnt
> Basics links

- source/development/workflow.rst
Hi there,
I added a link to the wikipedia article on ABI for starting developers.
Cheers,
tpltnt
> added wikipedia link for ABI

- source/development/guidelines/peps.rst
Hi there,
I linked to PEP8 and a style checker for the Python guidelines.
Cheers,
tpltnt
> linked to PEP8 and style checker

- source/manual/how-tos/proxytransparent.rst
- source/manual/how-tos/shaper.rst
> fix shaper heading; add note about Android

- source/manual/aliases.rst
- source/manual/ips.rst
- remove GeoIP via Suricata in Alias section
- fix typo
- add URLHaus
- add app detect rules
> some updates

- source/manual/how-tos/openconnect.rst
- source/manual/vpnet.rst
Short introduction, should I add a screenshot too?
> openconnect howto

- source/development/api/plugins/netsnmp.rst
- source/development/api/plugins/ntopng.rst
- source/development/api/plugins/vnstat.rst
- source/development/api/plugins/wireguard.rst
- wireguard
- netsnmp
- ntopng
- vnstat
> new api docs

- source/manual/dynamic_routing.rst
> Add tunable warning to dynamic_routing.rst

- source/manual/how-tos/carp.rst
While discussing ... https://github.com/opnsense/core/issues/2795
> carp: add a note for multiple carp ip's

- source/manual/how-tos/cellular.rst
I've extended the cellular modem howto quite a bit, as I had troubles getting my to card work. Everything I figured out so far is represented in the changes and should help other users debugging their setup, in case not everything works out of the box.
Note that I did not write RST so far, maybe someone can check if my syntax is correct. Preview in github looks ok but I could for example not test the "info" boxes.
> Extend the cellular modem howto

- source/development/api/plugins/backup-api.rst
Added documentation after Pull Request https://github.com/opnsense/plugins/pull/895
> Adding documentation for  `backup-api`

- source/manual/logging.rst
With the PR to core merged, also change the order in the docs.
> Reorder remote logging settings

- source/manual.rst
- source/manual/nat.rst
This page links to the nptv6 page I wrote earlier (but hasn't been merged yet).
> Create page about NAT

- source/relations/m0n0wall.rst
The last sentence was not grammatically correct and more or less said the opposite of what was intended.
> Fix last sentence of m0n0wall article

- source/manual/captiveportal.rst
> captiveportal.rst - typo

- source/manual.rst
- source/manual/how-tos/user-local.rst
- source/manual/settingsmenu.rst
~~There are more section I want to cover here, but I figured I'd open the PR now, so @fabianfrz (or another member) can give feedback early.~~ All subjects under System --> Settings are now covered.
> Add page about System --> Settings

- source/manual/install.rst
> Fix Installation media table

- source/manual/how-tos/proxywebfilter.rst
As discussed with @AdSchellevis in IRC
> Add note to file extension for RACL

- source/manual/how-tos/wireguard-client-azire.rst
- source/manual/how-tos/wireguard-client-mullvad.rst
- source/manual/how-tos/wireguard-client.rst
- source/manual/how-tos/wireguard-s2s.rst
Before going stable with the plugin, update to latest wording
> wireguard: rename server to local 

- source/development/api/plugins/dnscryprproxy.rst
> Add DnsCrypt API documentation

- source/manual/how-tos/wireguard-client.rst
Corrected a small sentence issue
> :pencil2: typo in Wiregard documentation

- source/manual/how-tos/wireguard-client-azire.rst
- source/manual/how-tos/wireguard-client-mullvad.rst
- source/manual/how-tos/wireguard-client.rst
- source/manual/how-tos/wireguard-s2s.rst
> remove dev warning

- source/firewall.rst
- source/manual/logging.rst
- source/system.rst
as discussed with @AdSchellevis via IRC
> mv logging to system and add remote logging support

- source/manual/how-tos/multiwan.rst
https://forum.opnsense.org/index.php?topic=14036.0
> MultiWAN: add a note for default gateway switching

- source/manual/how-tos/proxyicapantivirus.rst
Update link to EICAR. Similar issue for a different page. Resolves #206
> Update EICAR link

- source/manual/how-tos/proxyicapantivirusinternal.rst
Updated the reference to EICAR to the new download page.
Fixes #206
> Update link to EICAR

- source/manual/dynamic_dns.rst
update documentation for cloudflare fields.
Closes opnsense/plugins#1045
Closes opnsense/plugins#1533
> Update for cloudflare fields

- source/development/backend/modelConstraints.rst
> #212: add contraints by me to doc

- source/contribute.rst
small change just for convenience: linked forum & irc in sections "reporting issue" and "forum & irc"
> linked forum & irc

- source/manual/how-tos/proxytransparent.rst
> update menu path label for proxy

- source/manual/proxy.rst
> minor change: two typos

- source/manual/how-tos/proxywebfilter.rst
I'm no English native speaker, but assume that the proxy is neutral and not male. Please double check with a native speaker to ensure that this change really improves the text and doesn't make it worse!
> gender of proxy

- source/manual/how-tos/clamav.rst
Added one small introduction sentence to clarify the usage of clamav within OPNsense a little.
Shall fix #222
> added intro

- source/manual/how-tos/maxmind_geo_ip.rst
> Change all references of "Licence" to "License" to comply with Maxmind URL

- source/manual/how-tos/maxmind_geo_ip.rst
Mention to choose wich version of key creation. fixes #232
> improve description on how to create license key

- source/development/frontend/routing.rst
Move text out of literal block used for the file path.
> fix formatting

- source/manual/unbound.rst
As a followup to opnsense/core#4208 this is the additional documentation for the unbound extension point in OPNSense.
Best regards
Sönke
> Unbound: Added documentation for advanced configurations

- source/manual/monit.rst
https://forum.opnsense.org/index.php?topic=17967.0
> Monit: Third example

- source/manual/radvd.rst
RFC 6106 has been obsoleted by 8106
> Updated RDNSS RFC from 6106 to 8106

- source/manual/virtuals.rst
Update regarding KVM that more accurately reflects the current status.
> Updated KVM info

- source/manual/how-tos/tayga.rst
- source/plugins.rst
Includes the pending changes from https://github.com/opnsense/plugins/pull/1826. Proofreading welcome.
> Create Tayga NAT64 how-to

- source/manual/how-tos/wireguard-s2s.rst
Fixed spelling of the word "remote"
> Fixed typo

- source/manual/aliases.rst
update aliases.rst for new feature: Address exclusions
> update aliases.rst for new feature: Address exclusions

- source/troubleshooting.rst
- source/troubleshooting/openvpn.rst
closes https://github.com/opnsense/core/issues/4485
Add instructions how to work around OpenVPN issues with reply-to in firewall rules
> Add section about OpenVPN assigned interfaces

- source/manual/how-tos/user-ldap.rst
> Adding better instructions on activating LDAP auth

- source/development/api/core/firewall.rst
- source/manual/aliases.rst
> added notes regarding the alias flush function; Fixes #4196

- source/manual/ips.rst
I found a few of the paragraphs confusing when I read through this so this is my attempt to make them more readable. Of course, I have a hard time stopping once I start so the size of the edit grew quickly.
I think there is still some room for improvement in this document. In particular, the title is about IPS but the default when enabling this service is IDS and yet that is barely mentioned. I think more attention needs to go into defining the systems, when to use which, and how to decide which to use. I have next to zero experience with either of these so I can't write anything authoritative.
> Editing and adding links to IPS page

- source/manual/how-tos/wireguard-client-mullvad.rst
- source/manual/how-tos/wireguard-selective-routing.rst
- source/plugins.rst
This pull request is to add a how-to to the OPNsense documentation that describes how to implement selective routing with WireGuard with an external VPN provider. The how-to is based on this forum [tutorial](https://forum.opnsense.org/index.php?topic=21205.msg99309#msg99309).
> Wireguard selective routing how-to

- source/manual/how-tos/wireguard-selective-routing.rst
Address DNS resolution on OPNsense and DNS leaks
> WG selective routing how-to: DNS related updates

- source/relations/freebsd.rst
Tiny tiny PR to update 'build' --> 'built' and 'joy full' --> 'joyful' in in docs/source/relations/freebsd.rst
Thanks - keep up the great work!
Alicia
> Small spelling corrections

- source/manual/nptv6.rst
> Update NPTv6 documentation

- source/manual/how-tos/carp.rst
Reworded some of the paragraph to make it easy to understand what outbound NAT settings need to be changed and why.
> Updated Setup outbound NAT section

- source/vendor/sunnyvalley/sensei.rst
- source/vendor/sunnyvalley/sensei_install.rst
Sunny Valley has changed the documentation platform. Updated URLs added in branch.@muratbalaban43 is the manager of Sunny Valley have been informed about that change.
> Sensei new documentation urls added

- source/vendor/sunnyvalley/sensei.rst
- source/vendor/sunnyvalley/sensei_install.rst
Hi,
Sunny Valley documentation updated 
https://www.sunnyvalley.io/docs/opnsense
/opensense added to URLS, 
@muratbalaban43 has been informed.
> opnsense-sensei docs urls updated

- source/manual/how-tos/wireguard-client.rst
Given some comments I've seen recently on the forum and Reddit from users who are confused by the existing how-to, I am suggesting a re-write to make it clearer and more step-by-step, while also adopting a similar structure to the selective routing how-to
> Rewrite of WireGuard client how-to

- source/history/thefork.rst
These improvements make the text more fluent to read, and more similar to mainstream English
> Adds some commas for fluency and some minor grammar improvements

- source/manual/aliases.rst
to be merged when https://github.com/opnsense/core/issues/4952 is included
> Firewall / aliases - add wildcard definition

- source/manual/how-tos/wireguard-client.rst
- source/manual/how-tos/wireguard-selective-routing.rst
Adding a specific warning regarding setting DNS servers in the WG road warrior how-to. Also fixing some formatting issues.
Adding instructions for IPv6 configuration in the WG selective routing how-to. Also fixing some formatting issues, and adding some other minor clarifications/explanations.
> WG road warrior/selective routing updates

- source/manual/how-tos/nut.rst
/ref https://forum.opnsense.org/index.php?topic=25581.0
> add more info what actually happens when nut is enabled

- source/manual/git-backup.rst
As suggested in https://github.com/opnsense/plugins/issues/2816.
> adding tip for github urls.

- source/manual/git-backup.rst
See https://github.com/opnsense/plugins/issues/2866 for reference.
> Add Gitlab to the URL format hint

- source/manual/monit.rst
> Fix typo in monit docs

- source/manual/aliases.rst
closes https://github.com/opnsense/core/issues/5913
> Firewall / Aliases - Add BGP ASN type

- source/vendor/sunnyvalley/zenarmor_hardwarerequirements.rst
- source/vendor/sunnyvalley/zenarmor_install.rst
Hello,
I edited Sunny Valley Page .
Updated some of the links from Zenarmor docs.
Murat Balaban @muratbalaban43 is informed for these changes.
Regards.
> Zenarmor Documentation Changes

- source/manual/virtuals.rst
dounting -> daunting
I googled online and couldn't find a source for dounting so I updated the spelling issue here. If this still happens to be a case of British vs American spelling, feel free to close this PR. 
Cheers!
> Fix spelling

- source/manual/certificates.rst
- source/manual/interfaces.rst
- source/manual/reverse_proxy.rst
- source/manual/vpnet.rst
- source/relations.rst
- source/security.rst
I made a few very minor changes for grammar and spelling.
> Minor doc fixes

- source/manual/monit.rst
Regarding this issue:
https://github.com/opnsense/core/issues/6337
> Added section "Advanced Configurations" for Monit

- source/troubleshooting/performance.rst
> Update performance.rst: typo

- source/manual/how-tos/insight.rst
> Update insight.rst: typo

- source/manual/how-tos/sslvpn_instance_roadwarrior.rst
As pointed out by **carbonator** in IRC.
> Fix typo'd port

- source/vendor/sunnyvalley/zenarmor.rst
- source/vendor/sunnyvalley/zenarmor_hardwarerequirements.rst
- source/vendor/sunnyvalley/zenarmor_install.rst
The broken links have been fixed. The updated links have been replaced with the old ones. Some punctuation issues have been resolved.
> Zenarmor patch 1

- source/manual/how-tos/carp.rst
I added a section for IPv6 CARP because I couldn't find it in the docs. In the forum there are questions regarding this occasionally.
I was also affected by this in the past because I misinterpreted the section: 
"If you want to add an IPv6 CARP address, write your IPv6 address and the dropdown list will auto-update to 128." 
https://forum.opnsense.org/index.php?topic=33157
I'm open to discussion.
> Update carp.rst - Add IPv6 CARP Section

- source/manual/updates.rst
Hello, 
A PR to change the path that indicates or upgrade packages. 
The "Check for updates" button is on the status page and not updates page. On Update we only have the Update button. But the check must be check befor (on status page) ?
Have a nice day.
> Change path for update

- source/manual/how-tos/multicast-dns.rst
Upstream documentation:
https://github.com/geekman/mdns-repeater/blob/fbe78e7ffddee8f1dd16a4a990a0b86f94a85964/mdns-repeater.c#L330
> mdns-repeater only supports up to 5 interfaces

- source/manual/install.rst
This PR fixes a really small typo.
Thank you for maintaining this awesome application. :bouquet:
> Typo applcation => application

- source/manual/how-tos/dnscrypt-proxy.rst
> Remove duplicated words in dnscrypt-proxy.rst

- source/manual/unbound.rst
Updated to coincide with my changes in https://github.com/opnsense/core/pull/7103
I also fixed the NoCoin URL to match what was already in place in core
> Unbound: Update predefined blacklist sources

- source/manual/how-tos/edrop.rst
I made a typo in #533 :see_no_evil:
> Fix typo in link

- source/manual/how-tos/sslvpn_instance_s2s.rst
I believe there are some minor errors in the guide to enable a site-to-site openvpn solution.
This PR aims to fix these minor errors
> Minor fixes to site-to-site openvpn guide

- source/manual/how-tos/caddy.rst
- source/manual/reverse_proxy.rst
- source/plugins.rst
Converted the Readme to a doc article. Will need some more proof reading and some style touch ups. But overall its something to start with and the information in it is correct.
https://github.com/opnsense/docs/issues/543
I improved the style, spelling and information. I think it's okay to be merged as a first version so users have something to refer to when the plugin appears.
> www/caddy: Documentation

- source/manual/how-tos/caddy.rst
https://github.com/opnsense/plugins/pull/3865
> www/caddy: TLS Insecure Skip Verify added to docs

- source/manual/how-tos/wireguard-client.rst
see https://github.com/opnsense/docs/issues/549
> wireguard: fix the order of steps in docs

- source/manual/how-tos/sslvpn_instance_roadwarrior.rst
https://github.com/opnsense/core/issues/7318
> Added note to create NAT outbound rule for redirect-gateway to work

- source/manual/how-tos/caddy.rst
Small typo,
forgot : in .. Note::
> Update caddy.rst - forgot : in .. Note::

- source/manual/how-tos/caddy.rst
For: https://github.com/opnsense/plugins/issues/3935
> Update caddy.rst for www/caddy: v1.5.5

- source/manual/how-tos/caddy.rst
- Explain how to use the DEBUG log
- Activation and usage of the admin endpoint of Caddy for live profiling and debugging.
> Update caddy.rst - Added advanced troubleshooting section

- source/manual/how-tos/caddy.rst
Reformat Docs for Caddy:
- Improve Maintainability by removing the options with their help texts. Having them only in the Plugin is better maintainable. It's also mostly a wall of text nobody reads, the Tutorial sections are the interesting thing.
- Everything is synced with latest version v1.5.5.
- Reformatted for better readability.
> www/caddy: Synchronize with v1.5.5

- source/manual/how-tos/caddy.rst
Fixes: https://github.com/opnsense/docs/issues/564
Using "|" creates spaces between lists. Implemented for better readability when the lists have 3 or more items.
https://sphinx-rtd-theme.readthedocs.io/en/stable/demo/demo.html#line-blocks
> www/caddy: Fix build warnings, adjust some typos, make some sections clearer.

- source/manual/settingsmenu.rst
Hi @AdSchellevis. Hier ben ik weer ;)
- Rename "Disable web GUI redirect rule" to "Http Redirect"
- Add missing "Login Messages" option
- Explain "Time zone"
- Explain "Prefer to use IPv4 even if IPv6 is available"
- Explain all "Power mode" settings
> Add missing options & extend or remove settings

- source/be.rst
> Small grammar & layout fixes on BE page

- source/manual/how-tos/caddy.rst
os-caddy-1.6.1 will be in OPNsense 24.7 and is the feature complete version of the plugin for now.
Please merge when 24.7 comes out.
> www/caddy: os-caddy-1.6.1

- source/vendor/deciso/opncentral.rst
Fixes: https://github.com/opnsense/docs/issues/588
> opncentral.rst - Add tutorial for automatic WebGUI login

- source/manual/how-tos/bind.rst
> bind.rst - fix spelling

- source/manual/boot_environment.rst
- source/manual/snapshots.rst
- source/system.rst
Fixes: https://github.com/opnsense/docs/issues/592
> system/snapshots: Add initial documentation for boot environments

- source/development/components/menusystem.rst
- source/development/frontend/controller.rst
- source/development/frontend/models_fieldtypes.rst
- source/development/frontend/models_migrations.rst
- source/development/frontend/view_js_helpers.rst
> docs: Fix typo

- source/vendor/deciso/opnwaf.rst
This improves the docs with a mix of new features that come for OPNWAF.
Since these features are spread across 2 versions of OPNsense Business edition, these features have been marked with their first appearance in present or future versions, so its clear for the user if they have them or not depending on their OPNsense version.
> deciso/OPNWAF: Include new features into OPNWAF documentation

- source/hardware/sfp_compatibility.rst
Added the fs.com XGS-ONU-25-20NI XGSPON module. Tested and working on a DEC750 with Odido Netherlands XGSPON service.
> Update sfp_compatibility.rst with FS XGS-ONU-25-20NI

- requirements.txt
- source/conf.py
Took the idea from https://github.com/readthedocs/sphinx_rtd_theme/issues/1240 and resolved the issue in https://github.com/opnsense/docs/commit/15be11c750ae9738d6e6427b8cf92e5dd0103ba0.
> Fix support for newer sphinx_rtd_theme versions up to 2.0

- source/manual/how-tos/sslvpn_instance_roadwarrior.rst
Also make steps use same formatting as above two paragraphs and fix minor formatting issues
> Select OpenVPN CA as issuer of OpenVPN user cert

- requirements.txt
- source/conf.py
This can help with showing off options in tabs like they appear inside the OPNsense WebGUI without cluttering the docs pages too much.
It looks very intuitive, it's easy to set up in the restructured text files, and it's natively supported by sphinx.
```
.. tabs::
.. tab:: General
=================================== =======================================================================================================================
Options                             Description
=================================== =======================================================================================================================
**enable**                          This will activate the RIP service.
**Version**                         Choose your RIP version (1 or 2). 1 is classful, …
```
> docs: Add sphinx-tabs support

- source/manual/how-tos/wireguard-client-mullvad.rst
- source/manual/how-tos/wireguard-selective-routing.rst
Changed a typo regarding adding DNS to a peer. 
Also added additional direction to a note regarding gateway configuration.
> Minor changes and updates

- source/manual/how-tos/maxmind_geo_ip.rst
- Added instructions to update account ID as it is needed for the URL to work. 
- Updated the reference on the license key to exactly match the example URL.
- Cleaned up the sentence.
> MaxMind - added in accountID update

- source/manual/how-tos/ipsec-rw-srv-eapradius.rst
- source/manual/how-tos/ipsec-rw-srv-eaptls.rst
- source/manual/how-tos/ipsec-rw-srv-ikev1xauth.rst
- source/manual/how-tos/ipsec-rw-srv-rsamschapv2.rst
- source/manual/how-tos/ipsec-swanctl-rw-ikev2-eap-mschapv2.rst
- source/manual/how-tos/proxytransparent.rst
- source/manual/how-tos/self-signed-chain.rst
- source/manual/how-tos/sslvpn_client.rst
- source/manual/how-tos/sslvpn_instance_roadwarrior.rst
- source/manual/how-tos/sslvpn_instance_s2s.rst
- source/manual/how-tos/stunnel.rst
- source/vendor/deciso/opncentral.rst
WIP
Explain the why and the how in a more generalized way. Remove pictures for maintainability.
Fixes: https://github.com/opnsense/docs/issues/628
Fixes: https://github.com/opnsense/docs/issues/599
> system/trust: Rewrite self signed chain tutorial

- source/manual/how-tos/ipv6_fb.rst
fixing not found error on AVM page. Unfortunately, did not find any way to permalink.
> Update ipv6_fb.rst, typo fix in external AVM URL

- source/firewall.rst
- source/manual/firewall_groups.rst
- source/manual/how-tos/maxmind_geo_ip.rst
- source/manual/how-tos/security-zones.rst
- source/manual/how-tos/vlan_and_lagg.rst
Fixes: https://github.com/opnsense/docs/issues/606
Requires:
https://github.com/opnsense/core/commit/4789c2a7527190d3848510a1af7fccb90761eb7d
https://github.com/opnsense/core/commit/1293c51187768ca527ec337771a35e8ea16afcc9
https://github.com/opnsense/core/commit/0dac1d62012dac4ce0f8b00754586cf381caee9b
> firewall: Add security-zones.rst explaining zone based firewall rules

- source/manual/how-tos/cellular.rst
Add link to supported u3g (a.k.a. cellular) devices for the latest FreeBSD.
> Add link to supported u3g devices

- source/manual/how-tos/ipsec-swanctl-rw-ikev2-eap-mschapv2.rst
Fixes: https://github.com/opnsense/docs/issues/639
Fixes: https://forum.opnsense.org/index.php?topic=44061
Fixes: https://github.com/opnsense/docs/issues/623
> vpn/ipsec: Add additional information to swanctl roadwarrior docs

- source/manual/settingsmenu.rst
> Update settingsmenu.rst: typo

- source/manual/how-tos/wireguard-client.rst
suggesting better phrasing to clarify instructions
> Clarify WireGuard Road Warrior Setup doc

- source/manual/settingsmenu.rst
Changes for https://github.com/opnsense/core/pull/8206
> Update settingsmenu.rst for new sshd_config overrides

- source/manual/ndproxy.rst
PR: https://forum.opnsense.org/index.php?topic=44071.msg229789#msg229789
> net/ndproxy: MAC address should be of WAN interface

- source/manual/how-tos/pppoe_isp_setup.rst
- source/manual/other-interfaces.rst
Fixes: https://github.com/opnsense/docs/issues/668
> devices: Add Point-to-point to general overview and add how-to for ISP setup with PPPoE

- source/vendor/deciso/opnwaf.rst
Fixes remark here:
https://github.com/opnsense/plugins/issues/4625#issuecomment-2758353704
> opnwaf: Make finished exchange server configuration more explicit

- source/manual/dnsmasq.rst
Fixes: https://github.com/opnsense/docs/issues/677
> dnsmasq: Rewrite docs page for new version including DHCP

- source/manual/dnsmasq.rst
https://github.com/opnsense/core/pull/8516
> dnsmasq: Update docs to reflect dhcp-option and dhcp-match merge

- source/manual/how-tos/caddy.rst
Just a quick cleanup, also removing some stale information about requesting DNS providers on github and updating some terminology.
> www/caddy: Update docs to reflect terminology changes

- source/manual/how-tos/pppoe_isp_setup.rst
I read some feedback on the forum and reddit with people struggling with this guide, so I double checked and corrected the mistake in it.
> pppoe: Correct isp setup guide

- source/development/how-tos/api.rst
Fixes: https://github.com/opnsense/docs/issues/688
> api: Guide how to use browser console to inspect API

- source/security.rst
Noticed these while reading, figured I'd send in a PR
> security: Fix minor typos

- source/troubleshooting.rst
- source/troubleshooting/config_reset.rst
If needed this myself quite a few times when I locked myself out (e.g. user manager), and it helped some users via email support.
A guide is a logical choice.
> troubleshooting: Add section for restoring config.xml from backup cache via serial console

- source/manual/firewall.rst
Fixes: https://github.com/opnsense/docs/issues/700
> firewall: Add multiselection hints

- .github/ISSUE_TEMPLATE/question.md
Instead is the current spelling, In stead is now archaic
> Update question.md English grammar

- source/manual/dnsmasq.rst
Simplify the example a bit as discussed.
> dnsmasq: Add PTR Records, remove manual setting of router and dns options

- source/manual/dynamic_routing.rst
Possible docs update for https://github.com/opnsense/plugins/pull/4694
Please wait if/until it gets merged.
> net/frr: update docs

- source/manual/dnsmasq.rst
Fixes: https://github.com/opnsense/docs/issues/726
> dnsmasq: Add value of DHCP option, add common RA mode values

- source/manual/how-tos/caddy.rst
For: https://github.com/opnsense/plugins/commit/a5fdb9ccd1ccdf885156a702cda8920f08bb16fd
> www/caddy: Remove DNS providers except Cloudflare for os-caddy-2.0.0

- source/manual/dnsmasq.rst
Fixes: https://forum.opnsense.org/index.php?topic=47221
> dnsmasq: Add dhcp boot section to docs

- source/manual/dnsmasq.rst
Checked via wireshark, there are way more options being sent but these are the ones that peak the most interest for common usecases.
PR was some discussion in the forum but I do not find the post anymore.
> dnsmasq: Specify default DHCP options better

- source/manual/dnsmasq.rst
For: https://github.com/opnsense/core/issues/8711
> dnsmasq: Fix DHCP reservation manual

- source/manual/dhcp.rst
- source/manual/dnsmasq.rst
Still had some feedback that default was missing, so I restructured it completely to make the flags more obvious.
> dnsmasq: Sort ra modes via RA flags, add local directive to host

- source/manual/firewall_generic.rst
Hey,
The [Interface] Network wording was confusing to me. I've made very slight modifications to make it more clear what is being said. Please make sure it is still the idea you want to convey before merging.
Thanks!
> Minor grammar fixes and rewording [Interface] Network

- source/manual/dynamic_routing.rst
For: https://github.com/opnsense/plugins/pull/4722
> net/frr: Add Listen Ranges to Peer Group documentation

- source/development/examples/using_grids.rst
Fixes: https://github.com/opnsense/docs/issues/659
Requires: https://github.com/opnsense/plugins/pull/4815
> devel/grid_example: Update documentation for base_bootgrid_table and base_apply_button
